version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - JWT_SECRET=test-paafff
      - DATABASE_URL=postgres://postgres:sqlpaafff@db:5432/db_dummy?schema=public
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sqlpaafff
      POSTGRES_DB: db_dummy
    ports:
      - '5433:5432'
